### ISSUE TITLE
Does this project work correctly?

### ISSUE THREAD

**Issue by bruteforks** [Javin-Juneja/Motion_Matching#1]
Trying to learn from other people's implementation. Wondering if this is functional? I tried updating it with my settings, but character was still a-posed.

thanks

**Comment by Javin-Juneja** [comment]
Hey, yeh this projects works, of I may know, what changes did you make?

**Comment by bruteforks** [comment]
Ahh I'm sorry, that's my fault. Which engine version does this use? I converted project to 5.3 and then tried updating to match my 5.3 implementation. I have setup a motion matching discord. let me know if you would like the link.

**Comment by Javin-Juneja** [comment]
Its using, 5.2. Since its still a WIP it might not work properly. I'll be glad to be a part of that discord :)

**Comment by bruteforks** [comment]
ahh thanks for the info

https://discord.gg/JXp5nKTvRR
